In the commify answer, drop Number::Format for CLDR::Number
perl-doc-cats/perlfaq pull request #108
Opened 2023-08-13 01:33 UTC by briandfoy

For #88

2023-08-14 09:36 UTC, davorg approved these changes

2023-09-05 16:48 UTC, briandfoy commented
What needs to happen for this to move forward?

2023-09-13 16:12 UTC, briandfoy commented
This PR has been approved. What needs to happen for it to be merged?

2023-10-10 22:01 UTC, briandfoy commented
I'm dropping the patch file here for when I delete my fork later this month. If a PR isn't going to go forward, I need it out of my queue of open things.

[0001-In-the-commify-answer-drop-Number-Format-for-CLDR-Nu.patch](https://github.com/perl-doc-cats/perlfaq/files/12862134/0001-In-the-commify-answer-drop-Number-Format-for-CLDR-Nu.patch)

2023-10-15 02:56 UTC, karenetheridge requested changes

2023-10-15 02:56 UTC, karenetheridge commented on lib/perlfaq5.pod
> +anything that you might want. Olaf Anders article "Stop Writing Your Own
```suggestion
anything that you might want. Olaf Alders' article "Stop Writing Your Own
```

2023-10-15 02:56 UTC, merged