Update the list of Perl editors
perl-doc-cats/perlfaq pull request #112
Opened 2023-10-10 22:50 UTC by briandfoy

For #83

2023-10-11 18:23 UTC, wchristian commented
while komodo is not actively developed anymore, it can still be downloaded and still works, and provides some features others don't have, or provide only in a degraded fashion, such as fully featured realtime debugging

2023-10-12 10:56 UTC, davorg commented on lib/perlfaq3.pod
> +=ver 4
`=over`

2023-10-12 10:56 UTC, davorg commented on lib/perlfaq3.pod
> +USe the L<Perl plugin from the Jet Brains marketplace|https://plugins.jetbrains.com/plugin/7796>.
"Use"

2023-10-12 12:55 UTC, smonff requested changes

2023-10-12 12:55 UTC, smonff commented on lib/perlfaq3.pod
> +USe the L<Perl plugin from the Jet Brains marketplace|https://plugins.jetbrains.com/plugin/7796>.
"JetBrains", no space.

2023-10-12 12:55 UTC, smonff commented on lib/perlfaq3.pod
> +Use cperl-mode.
```suggestion
Use cperl-mode and L<lsp-mode|https://emacs-lsp.github.io/lsp-mode>.
```

2023-10-12 16:17 UTC, hurricup commented on lib/perlfaq3.pod
> +=item L<WebStorm|https://www.jetbrains.com/webstorm/>
Webstorm as well as other jetbrains IDEs  (RubyMine, PhpStorm, PyCharm, etc. see [supported products](https://plugins.jetbrains.com/plugin/7796-perl/versions/stable/412532)) supporting perl only with perl plugin mentioned above. Well, you may have a textmate highlighting without it, but that's it. Any code intelligence, profiling, coverage, debugging and so on provided by the plugin.

2023-10-13 09:37 UTC, wchristian commented
to be clear: addressing mine and mst's comment is not optional

2023-10-13 09:41 UTC, wchristian requested changes
justify all deletions

2023-10-13 12:33 UTC, briandfoy commented
Some people want to list Komodo, but it's abandoned and its own page says it has stability issues on macOS. There is no support for this editor and people just starting who need this advice shouldn't choose something that was abandoned two years ago. Other editors are likewise unsupported, abandoned, or too onerous to install for those who need this basic advice. 

It's not like people have a hard time finding a Windows IDE now that Visual Code supports Perl.

I've taken this patch as far as I'm going to take it. If the maintainers want to include different editors, they can contribute to the PR. I've added my parts, the community can add other parts. If someone wants a particular editor in the list, they can add their commit to the PR so people can see who suggested that editor.

2023-10-15 05:53 UTC, wchristian commented
@briandfoy In the past you have claimed the nazi party of germany was left wing and justified perl-community-affecting action based on that. You were factually false then. Your action was wrong then. Your further response then was dehumanizing, dishonest, egotistical and refused actual dialogue.

Now much of this applies again.

I will be taking this patch forward so people will be guided by experience and knowledge.

2023-10-15 07:04 UTC, hurricup commented
Why not just mention abandoned editors as abandoned editors user could use on their own risk?

2023-10-15 11:52 UTC, wchristian commented
Yep, i will be explaining that. It is also not only abandoned, but open-sourced. And there are things visual code can't do right yet, which work just fine in Komodo.

2023-10-15 11:57 UTC, hurricup commented
@wchristian try community Intellij IDEA with perl plugin. Both opensource and free. And smarter than Komodo.

2023-10-15 12:14 UTC, wchristian commented
Last time i evaluated intellij, the perl plugin for it only provided crude debugging. But i will be evaluating things on the list to have up-to-date info.

2023-10-15 21:53 UTC, closed without merging